### ISSUE TITLE
Форма отзывов

### ISSUE THREAD

**Issue by KHOnKOgaB** [knowhow-agency/Realtpro#108]
<img width="581" alt="Снимок экрана 2019-08-26 в 15 25 01" src="https://user-images.githubusercontent.com/30749005/63690601-c2d33200-c815-11e9-97ac-6a5c25d3b606.png">
Нужно сделать из этого окна обычный див - слева картинка, справа - отзыв. Чтоб они могли эти отзывы вставлять через админку.

**Comment by vasilievruslan** [comment]
https://github.com/knowhow-agency/Realtpro/pull/121
