### ISSUE TITLE
Страница "о нас" - добавить внизу блок под общую фотограию

### ISSUE THREAD

**Issue by KHOnKOgaB** [knowhow-agency/Realtpro#117]

**Comment by vasilievruslan** [comment]
Дело на 5сек только фотку дай

**Comment by KHOnKOgaB** [comment]
https://drive.google.com/open?id=1t5LL5Cy3HlrOepcuE6PUUt0b34s1e0tC

**Comment by KHOnKOgaB** [comment]
Попробуй так. Правда она весит 7 мб. Щас еще в телегу отправлю как фотку

**Comment by vasilievruslan** [comment]
https://github.com/knowhow-agency/Realtpro/pull/125
