### ISSUE TITLE
Страница "Ремонт" - добавить блок с примерами фотографий ремонта. 

### ISSUE THREAD

**Issue by KHOnKOgaB** [knowhow-agency/Realtpro#118]
Поскольку у их партнеров существует три вида ремонта, предлагаю этот блок сделать состоящим из трех колонок - эконом, стандарт, премиум.
Каждая колонка - это карусель, внутри которой крутятся фотки примеров. 
<img width="556" alt="Снимок экрана 2019-08-27 в 17 29 47" src="https://user-images.githubusercontent.com/30749005/63780111-495c4200-c8f0-11e9-80df-27098223c352.png">

Без точек внизу, без элементов управления. Пусть просто листается автоматически

**Comment by vasilievruslan** [comment]
https://github.com/knowhow-agency/Realtpro/pull/126
