### ISSUE TITLE
Изменить верхний подвал

### ISSUE THREAD

**Issue by KHOnKOgaB** [knowhow-agency/Realtpro#132]
<img width="1195" alt="Снимок экрана 2019-09-03 в 11 48 21" src="https://user-images.githubusercontent.com/30749005/64158229-c3388200-ce40-11e9-86d3-45dd2592403f.png">

Сделать 3 колонки по 1 пункту меню -
Школа риелторов          Вакансии          Ипотечный калькулятор

**Comment by vasilievruslan** [comment]
https://github.com/knowhow-agency/Realtpro/pull/136
