### ISSUE TITLE
Проблема между редактором текста в админке и текстами на сайте

### ISSUE THREAD

**Issue by KHOnKOgaB** [knowhow-agency/Realtpro#145]
Вот так текст выглядит в админке. Двойными звездочками обозначается жирный шрифт.
![Снимок экрана 2019-09-05 в 14 34 16](https://user-images.githubusercontent.com/30749005/64338399-52cd6480-cfea-11e9-9407-7b436987d4a8.png)

А вот так он выглядит на сайте:
![Снимок экрана 2019-09-05 в 14 33 58](https://user-images.githubusercontent.com/30749005/64338428-62e54400-cfea-11e9-9340-0dd1c79ad011.png)

**Comment by KHOnKOgaB** [comment]
На выходе теряются все отступы и форматирование текста

**Comment by vasilievruslan** [comment]
https://github.com/knowhow-agency/Realtpro/pull/147
