### ISSUE TITLE
Продумать интерактивность для кнопок при наведении в header

### ISSUE THREAD

**Issue by KHOnKOgaB** [knowhow-agency/Realtpro#157]
<img width="1131" alt="Снимок экрана 2019-09-09 в 17 30 31" src="https://user-images.githubusercontent.com/30749005/64539682-98aa6580-d327-11e9-9327-7b24144e38b7.png">

Может свечение какое-то сделать или обводку?

**Comment by vasilievruslan** [comment]
@KHOnKOgaB всмысле на hover сделать что нибудь?
