### ISSUE TITLE
Добавить контент

### ISSUE THREAD

**Issue by vasilievruslan** [knowhow-agency/Realtpro#18]
Добавить объекты разных типов и категорий которые есть в фильтре
[REALTpro filter.pdf](https://github.com/knowhow-agency/Realtpro/files/3416577/REALTpro.filter.pdf)

**Comment by anchazzz** [comment]
короче, я начала вбивать в таблицу те данные, которые они прислали... это дичь, потому что нет ни одного полностью заполненного объекта
но хоть так. 
Я не знаю, кто должен посмотреть, но посмотрите: удобно, если в таком формате будет таблица, данные? все понятно?
https://docs.google.com/spreadsheets/d/1pjde8YshZgFhqPc74mtHltIKJdoA5svso8uKlnVh20M/edit#gid=0
