### ISSUE TITLE
Добавить мета данные для страниц, title, description, og:tags

### ISSUE THREAD

**Issue by vasilievruslan** [knowhow-agency/Realtpro#24]
Мета данные для продвижения и отображения в заголовке вкладки
![Снимок экрана 2019-07-23 в 3 22 52 ПП](https://user-images.githubusercontent.com/17727527/61713631-b57fdf00-ad61-11e9-99c2-616defe2164e.png)
![Снимок экрана 2019-07-23 в 3 23 43 ПП](https://user-images.githubusercontent.com/17727527/61713639-b87acf80-ad61-11e9-85d2-b39737d495cb.png)

Типа вот этого

**Comment by anchazzz** [comment]
https://docs.google.com/document/d/1CSVxoEPEdA00PZ6HuOX2Ym6CWMeZ9fkPcOah5RSSjrQ/edit
