### ISSUE TITLE
Уменьшить фото менеджеров

### ISSUE THREAD

**Issue by vasilievruslan** [knowhow-agency/Realtpro#41]
Сейчас по 5мб весит. Нужно посмотреть размер окна в фигме и сделать им разрешение в 2 раза больше

**Comment by KHOnKOgaB** [comment]
Передал задачу иллюстратору. К среде фотографии будут готовы. 
По-необходимости сделают цветокоррекцию, уберут тени и уменьшат размеры.

**Comment by vasilievruslan** [comment]
Что то сложно как то, пусть тогда еще миниатюры сделают что б еще разгрузить сайт

**Comment by KHOnKOgaB** [comment]
Миниатюры сделали. Фотографии менеджеров сейчас сожмут

**Comment by vasilievruslan** [comment]
Так уже сделали? Просто карточка до сих пор в прогресс висит

**Comment by KHOnKOgaB** [comment]
Еще нет. Щас Саша сожмет фотки для главной страницы и я закрою заявку

**Comment by KHOnKOgaB** [comment]
Все, готово. Лови pull request
