### ISSUE TITLE
риЭлторы или риЕлторы?

### ISSUE THREAD

**Issue by KHOnKOgaB** [knowhow-agency/Realtpro#43]
У нас в контенте на сайте постоянно пишется то так, то так. Давайте придем к какому-то единому мнению и будем писать везде одинаково, а то, я думаю нам сделают замечание по этому поводу.

**Comment by anchazzz** [comment]
я ж вроде везде исправляла на риЕлторы

**Comment by anchazzz** [comment]
писать только так: через Е
