### ISSUE TITLE
Удалить из фильтров возможность "Сохранить поиск". Классная возможность, но в рамках данного проекта она нам не нужна

### ISSUE THREAD

**Issue by vasilievruslan** [knowhow-agency/Realtpro#48]

**Comment by vasilievruslan** [comment]
Это кстати не сложно, просто сохранить дату и ссылку которая сейчас в строке браузера

**Comment by KHOnKOgaB** [comment]
Ну смотри, если это не сильно отвлечет от разработки более существенных вещей, то ок, можем оставить
