### ISSUE TITLE
Предусмотреть возможность добавления/удаления/редактирования вакансий через кабинет администратора сайта

### ISSUE THREAD

**Issue by KHOnKOgaB** [knowhow-agency/Realtpro#51]
<img width="795" alt="Снимок экрана 2019-07-30 в 10 23 16" src="https://user-images.githubusercontent.com/30749005/62109065-31bf7880-b2b4-11e9-80bf-7d119ac46e53.png">

Вот этот блок

**Comment by vasilievruslan** [comment]
А как с картинками быть? У нас их 4 только, вдруг вакансий больше будет?

**Comment by vasilievruslan** [comment]
https://github.com/knowhow-agency/Realtpro/commit/fec6b96fbca54448eb87a3032c7f8e0673c7cb77

сделал
