### ISSUE TITLE
Кастомизация кнопки "вернуться наверх"

### ISSUE THREAD

**Issue by KHOnKOgaB** [knowhow-agency/Realtpro#61]
[arrow-top.svg.zip](https://github.com/knowhow-agency/Realtpro/files/3456388/arrow-top.svg.zip)
В архиве SVG файл со стрелкой сделанной в фирменном стиле Заказчика. Поменяй, пожалуйста.

**Comment by vasilievruslan** [comment]
Плохо экспортировали, там png внутри
