### ISSUE TITLE
Responsive footer bug

### ISSUE THREAD

**Issue by KHOnKOgaB** [knowhow-agency/Realtpro#85]
<img width="201" alt="Снимок экрана 2019-08-12 в 16 29 42" src="https://user-images.githubusercontent.com/30749005/62868540-8c2def80-bd1e-11e9-8081-96f09b570a2e.png">

На мобильной версии не работают иконки социальных сетей

**Comment by vasilievruslan** [comment]
https://github.com/knowhow-agency/Realtpro/pull/87 – есть
